const indianNames = [
  'Aarav',
  'Aarti',
  'Abhay',
  'Abhilasha',
  'Aditya',
  'Aditi',
  'Ajay',
  'Akanksha',
  'Akash',
  'Alok',
  'Amar',
  'Amita',
  'Amitabh',
  'Amrita',
  'Anand',
  'Ananya',
  'Anil',
  'Anita',
  'Anjali',
  'Ankur',
  'Anshul',
  'Anuja',
  'Arjun',
  'Arpita',
  'Arvind',
  'Aryan',
  'Ashok',
  'Asmita',
  'Atul',
  'Avani',
  'Ayush',
  'Bala',
  'Bhanu',
  'Bhavna',
  'Bijoy',
  'Bindu',
  'Bipin',
  'Chandra',
  'Charan',
  'Chhaya',
  'Chetan',
  'Chitra',
  'Damini',
  'Darshan',
  'Deepa',
  'Deepak',
  'Deepti',
  'Dev',
  'Devika',
  'Dhanraj',
  'Dilip',
  'Divya',
  'Eesha',
  'Ekta',
  'Falguni',
  'Gaurav',
  'Gayatri',
  'Geeta',
  'Girish',
  'Gopal',
  'Govind',
  'Harish',
  'Harsha',
  'Hema',
  'Hemant',
  'Himani',
  'Inder',
  'Indira',
  'Ira',
  'Ishaan',
  'Ishita',
  'Jagdish',
  'Jaya',
  'Jayant',
  'Jeevan',
  'Jitendra',
  'Jyoti',
  'Kabir',
  'Kajal',
  'Kamal',
  'Kamalini',
  'Karan',
  'Karthik',
  'Kavita',
  'Keshav',
  'Kiran',
  'Komal',
  'Krishna',
  'Kunal',
  'Lakshmi',
  'Lata',
  'Lavanya',
  'Lokesh',
  'Madhav',
  'Madhuri',
  'Mahesh',
  'Mamta',
  'Manish',
  'Manisha',
  'Manoj',
  'Meena',
  'Mihir',
  'Minal',
  'Mohan',
  'Mohini',
  'Mukesh',
  'Namita',
  'Namrata',
  'Nanda',
  'Nandini',
  'Narayan',
  'Neeraj',
  'Neha',
  'Nidhi',
  'Nikita',
  'Nilima',
  'Nishant',
  'Nisha',
  'Nitin',
  'Om',
  'Pallavi',
  'Parag',
  'Pooja',
  'Prachi',
  'Pradeep',
  'Prakash',
  'Praveen',
  'Preeti',
  'Priya',
  'Rahul',
  'Raj',
  'Rajat',
  'Rajesh',
  'Rajiv',
  'Raksha',
  'Ramesh',
  'Rani',
  'Ranjan',
  'Rashmi',
  'Ravi',
  'Ritu',
  'Rohit',
  'Rupali',
  'Sachin',
  'Sagar',
  'Sakshi',
  'Sameer',
  'Sandeep',
  'Sandhya',
  'Sanjay',
  'Santosh',
  'Sarita',
  'Sashi',
  'Satish',
  'Seema',
  'Sharad',
  'Shashi',
  'Sheetal',
  'Shekhar',
  'Shraddha',
  'Shravan',
  'Siddharth',
  'Sneha',
  'Sonali',
  'Sonia',
  'Soumya',
  'Sridhar',
  'Subhash',
  'Sudha',
  'Suman',
  'Sunil',
  'Suresh',
  'Swati',
  'Tanmay',
  'Tanvi',
  'Tanya',
  'Tarun',
  'Tejas',
  'Tushar',
  'Uday',
  'Uma',
  'Usha',
  'Vaibhav',
  'Vaishali',
  'Varun',
  'Veena',
  'Vikas',
  'Vikram',
  'Vinay',
  'Vinita',
  'Vishal',
  'Yash',
  'Yogesh',
];

export function generateRandomName() {
  return indianNames[Math.floor(Math.random() * indianNames.length)];
}

const youtubeComments = [
  'Bahut badhiya video!',
  'Amazing content, keep it up!',
  'Yeh video dekh kar maza aa gaya!',
  'Please make a tutorial on this topic.',
  'Kya mast editing ki hai!',
  'Aapke videos hamesha useful hote hain.',
  'Superb explanation, thanks a lot!',
  'Bhai, tumne toh kamaal kar diya!',
  'More videos on this topic, please.',
  'Aaj kuch naya seekhne ko mila!',
  'Perfect demonstration, really helpful.',
  'Aapki awaz kaafi soothing hai.',
  'Is this available in Hindi?',
  'Maza aa gaya dekh kar, thanks!',
  'Very creative, great job!',
  'Yeh kaunsa software use kiya aapne?',
  "Bro, you're underrated!",
  'Bhai, next video kab aa raha hai?',
  'Keep it up, you’ll grow soon!',
  'Hindi mein aur videos banao please.',
  'Kya mast concept samjhaya hai!',
  'This is exactly what I was looking for.',
  'How do you come up with such ideas?',
  'Editing toh zabardast hai!',
  'Aapke videos bahut inspiring hote hain.',
  'Nice tutorial, easy to understand.',
  'Ek request hai, is topic pe video banao.',
  'What a masterpiece, kudos!',
  'Bhai, tumhare jaise creators kam hote hain.',
  'Nice video! Waiting for the next one.',
  'Ye technique mujhe pehle kyun nahi pata chali?',
  'Aapki hard work clearly dikhti hai.',
  'Thanks for sharing this valuable content.',
  'Kya graphics banaya hai, awesome!',
  'Could you share the project files?',
  'Kitna easy samjhaya yaar!',
  'Love the quality of your videos.',
  'Sir, apse bahut kuch seekhne ko milta hai.',
  'Bro, apka sense of humor mast hai!',
  'Please collab with other creators too.',
  'Aapki knowledge amazing hai!',
  'Music aur video ka combo best hai!',
  "Can't wait for the next upload.",
  'Bhai, tumhare videos motivation se bhare hain.',
  'Great video, well done!',
  'Hindi content creators kaafi rare hain.',
  'Loved the way you explained it.',
  'Kya dedication hai bhai!',
  'Apne daily routine share karo please.',
  'Aapke channel ka fan ban gaya hoon.',
  'Bahut useful tips diye hain!',
  'Best part was the ending, hilarious!',
  'Editing skills level max hai bhai.',
  'I wish I had found your channel earlier.',
  'Keep doing this amazing work!',
  'Bahut accha laga yeh dekh kar.',
  'Your voice is so engaging!',
  'Full entertainment mila is video mein.',
  'Bhai, tumhe zyada views milne chahiye.',
  'Explained like a pro, thanks!',
  'Subscribe kar diya, awesome content!',
  'Comment section me sab impressed lag rahe hain.',
  'Such positivity in your videos!',
  'Yeh trick toh mast lagi!',
  'Your effort is visible in every frame.',
  'Keep inspiring us!',
  'Isse achha aur kya ho sakta hai?',
  'Thoda aur detail mein batate toh maza aata.',
  'Bhai, tumhare videos toh addict kar dete hain.',
  'Always learning new things here, thanks!',
  'Bina kisi bakwaas ke, straight to the point!',
  'Bhai, tumne apna level upar kar diya!',
  'Funny yet informative, great work!',
  'Could you upload more often, please?',
  'Yeh thumbnail kaafi attractive hai.',
  'Apka style bahut alag hai sabse.',
  'This is so satisfying to watch.',
  'Yeh channel ab mera favorite hai.',
  'Thanks for making this topic easy!',
  'Kitna mehnat karte ho yaar!',
  'Bro, yeh content next level hai.',
  'Aapka ek aur video trending hoga!',
  'Bahut hi accha breakdown diya hai.',
  'Ye wali playlist toh binge-worthy hai.',
  'Keep shining, bhai!',
  'Bhai, aapka editing sense next level hai.',
  'Aapka content sabse alag aur accha hai.',
  'Superb, maza aa gaya dekh ke!',
  'Please make a Q&A video soon.',
  'Best educational channel on YouTube!',
  'Jo aap sikha rahe ho, wo priceless hai.',
  'Your creativity knows no bounds.',
  'Ek advice dunga, aap aur bhi grow karoge!',
  'Fan ban gaya hoon aapka content dekh ke!',
  "Can't believe how good this is!",
  'Shuru se end tak maza aaya.',
  'Hats off to your dedication!',
  'Bhai, tumhare jaise creators ko support karna chahiye.',
];

export function generateRandomMessages() {
  return youtubeComments[Math.floor(Math.random() * youtubeComments.length)];
}
